### ISSUE TITLE
Autowired required a single bean, but 3 were found

### ISSUE THREAD

**Issue by g29times** [liuyangming/ByteTCC#101]
<dependency>
            <groupId>org.bytesoft</groupId>
            <artifactId>bytetcc-supports-springboot</artifactId>
            <version>0.5.3</version>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.cloud</groupId>
                    <artifactId>spring-cloud-zookeeper-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

***************************
APPLICATION FAILED TO START
***************************
Description:
Field accountService in com.abc.TestController required a single bean, but 3 were found:
单独跑demo可以的，但是集成到自己已有的Spring boot项目里的时候，Try cancle confirm 三个service实现导致启动失败，是少了配置吗？
@Compensable注解是有的

这块原理希望作者也能介绍下，是如何规避service实现类唯一性问题的？

**Comment by liuyangming** [comment]
有多个实现类时，需要用@Qualifier显式地注明具体使用哪一个实现；或者将某个实现（比如Try逻辑实现类）通过@Primary注解设置为默认。

**Comment by g29times** [comment]
但是在sample项目里面并没有配置@primary和@qualifier 也没报这个错误，我原以为是框架里面做了一些配置识别？ 另外，如果必须要设置的话，以try作为@primary可行？

**Comment by g29times** [comment]
我这边集成项目和sample项目表现不一致的除了上面，还有集成项目不能执行confirmService，已配置
@Compensable(interfaceClass = IAccountService.class,
        confirmableKey = "accountServiceConfirm",
        cancellableKey = "accountServiceCancel")

**Comment by liuyangming** [comment]
byteTCC允许controller不实现interfaceClass指定的接口，再加上springboot-sample/springcloud-sample用的是sagas模式没有confirm逻辑，因此实际上只有一个实现类。dubbo-sample中有三个实现类的配置，你可以参考一下。

**Comment by liuyangming** [comment]
可以将Try逻辑设置成@Primary，因为对于业务系统而言只有Try逻辑可见。confirm/cancel是业务系统提供给byteTCC回调的，业务系统不会直接调confirm/cancel，并且confirm/cancel也不对外暴漏，仅对byteTCC可见。

**Comment by g29times** [comment]
感谢 经验证将Try逻辑设置成@primary后可以正常使用
