### ISSUE TITLE
是否支持部分service方法事务生效

### ISSUE THREAD

**Issue by g29times** [liuyangming/ByteTCC#103]
有个service，有read()方法，有write()方法，最初只在write()方法增加了@Transaction，启动时报错，说read()方法没Transaction不行，在一个service里面不能只对部分方法生效吗？

**Comment by liuyangming** [comment]
byteTCC只检测interfaceClass指定接口中定义的方法。read操作不必用事务，就不必在interfaceClass指定接口中定义，也就可以不必定义@Transactional注解。但如果定义了，就需要加上。

**Comment by g29times** [comment]
OK
