### ISSUE TITLE
在自定义了一个aop，cancel不调用的问题

### ISSUE THREAD

**Issue by x6587305** [liuyangming/ByteTCC#105]
情况是这样的。我自定义了一个aop，然后只要当 feign 中出现 @RequestBody注解的时候。
cancel就不被调用。  即使我的aop并没有逻辑存在，并且 “@RequestBody”的方法并没有使用。
实际上我就是在提供的springcloud的demo上加了一个aop 然后在 IAccountService 接口中增加一个接口 @RequestMapping(method = RequestMethod.POST, value = "/test")
	public void increaseAmount(@RequestBody Map map);  就会出现这种情况。

**Comment by liuyangming** [comment]
只有Compensable.interfaceClass指定接口中定义了的方法，才是TCC服务。在interfaceClass指定接口中未定义的方法，走的是普通服务。

**Comment by x6587305** [comment]
你误解了我的意思。 我新增的 aop  和新增的 接口 并没有参与任何业务逻辑。 只是项目里面增加了这2个。您提供的原本的demo 就会失效。

**Comment by x6587305** [comment]
![1](https://user-images.githubusercontent.com/8153414/59664394-91216780-91e3-11e9-8cde-e7a6d83af9f5.png)
![2](https://user-images.githubusercontent.com/8153414/59664396-91b9fe00-91e3-11e9-8010-4c96ce7f4275.png)
我上传了 我新增的一个aop 和在接口上增加的一个接口的图片了。 如上：
实际上我是在我的项目中准备使用bytetcc，可是在一个服务上总是不可以。不知道怎么回事。然后就慢慢的移除代码才发现是这里的原因。然后我在您的demo中增加了这2个。会发现cancel不再调用

**Comment by liuyangming** [comment]
你所说的这个feign方法`public void increaseAmount(@requestbody Map map)`，在服务端springcloud-sample-provider工程中对应了AccountController中的一个方法，比如`public void newIncreaseAmount(@requestbody Map map)`，然而，byteTCC判断一个方法是不是TCC服务，依据的是该方法有没有在该Controller上@Compensable注解中的interfaceClass指定。
样例提供的increaseAmount/decreaseAmount都是在IAccountService（Compensable.interfaceClass指定的接口）中指定了的，而你新增的这个newIncreaseAmount(Map)则未必在该IAccountService（你前文中的IAccountService只是客户端feign接口，不是服务端Compensable.interfaceClass指定的接口）中定义，因此这个新增的服务就只是一个普通服务。

**Comment by x6587305** [comment]
不是。。 您还是在误解我的意思。。。 我加的接口并不使用。 我用的是您提供的demo。 逻辑还是 你demo里面的方法。 我新增的接口不调用的。 神奇就是神奇在这里。整个分布式事务的逻辑中并没有使用到我新增的 public void increaseAmount(@requestbody Map map) 这个方法。 
但是加了这个方法 却导致了本来可以正常使用的 下面的2个方法的cancel不被调用了。

**Comment by liuyangming** [comment]
好的，那我明白你的意思了。你的aop是怎么添加的？

**Comment by x6587305** [comment]
无论我去掉 aop 的代码。还是将feign 接口里面有 @requestbody注解的方法全部注释掉。 只要做了其中一项， cancel就能正常调用了

**Comment by x6587305** [comment]
整个demo 我就新增了一个aop文件 。和接口上加了一个新接口 代码都在上面的图上。wan完整的项目我上传了
[byte-tcc-test.zip](https://github.com/liuyangming/ByteTCC/files/3300516/byte-tcc-test.zip)

**Comment by liuyangming** [comment]
好的，那我明白你的意思了。我先看看，如果确认是一个bug，将会在下一个版本中予以修复。

**Comment by x6587305** [comment]
好的麻烦您了。 如果确定是bug 或者确定是我自己的问题。 麻烦您能告知一下嘛。。

**Comment by liuyangming** [comment]
你这个配置的问题在于，你自定义的aop拦截范围太大：`@Around("execution(* com.bytesvc..*(..))")`，
如果调整为：`@Around("execution(* com.bytesvc.consumer..*(..))")`就不会有这个问题了。

你定义的aop不仅拦截了普通的bean实例，而且也拦截了feign。一般来说，对feign的拦截最好是通过feign.RequestInterceptor来实现的，而不是aop。我印象中，spring-cloud好像强调feign需要独立分包放置，和普通bean实例相区别，未知是否是出于这个顾虑。

不过这个问题确实不容易发现，后续版本会考虑对该配置予以兼容，或至少予以友好提示。感谢反馈！

**Comment by x6587305** [comment]
明白了 非常感谢。
