### ISSUE TITLE
Compensable注解中的interfaceClass已有实现类，请问为何启动时依旧抛异常？

### ISSUE THREAD

**Issue by tianxin8206** [liuyangming/ByteTCC#116]
Compensable注解中的interfaceClass已有实现类，请问为何启动时依旧抛异常？
org.springframework.beans.FatalBeanException: Compensable-service(approvingController) does not implement method 'save' specified by the interfaceClass.

**Comment by liuyangming** [comment]
提示很明确了啊，Compensable服务(beanId为approvingController)没有实现interfaceClass配置接口中的save方法。

byteTCC为了方便业务系统开发，允许Controller不实现interfaceClass配置的接口，但是仍然还是要求它实现该接口中的所有方法。

**Comment by tianxin8206** [comment]
明白了，谢谢

**Comment by tianxin8206** [comment]
明白了，谢谢
