### ISSUE TITLE
想请教一下 并发场景下Confirm/Cancel的幂等性是如何保证的？不使用mongo的情况下是基于数据库bytejta插入时的唯一约束xid吗？使用mongo时用的是基于MongoCompensableLock？

### ISSUE THREAD

**Issue by nets7snipper** [liuyangming/ByteTCC#132]

**Comment by liuyangming** [comment]
byteTCC针对Confirm/Cancel的幂等保障，是以事务为单元来操作的。不同的事务之间互不影响，因此，并发与否，并无区别。

MongoCompensableLock用于保障某指定时刻一个服务只有一个集群实例参与当前全局事务，与幂等无关。

**Comment by nets7snipper** [comment]
谢谢大佬讲解，对于以事务为操作单元这个说法，我可以理解为同一个cofirm/cancel，由于预先分配了xid，因此最后提交事务时，对于同一个事务，即使多个线程同时执行commit，数据库只会接收其中一个线程的提交，其他的都会失败。

**Comment by nets7snipper** [comment]
谢谢大佬讲解，对于以事务为操作单元这个说法，我可以理解为同一个cofirm/cancel，由于预先分配了xid，因此最后提交事务时，对于同一个事务，即使多个线程同时执行commit，数据库只会接收其中一个线程的提交，其他的都会失败。

**Comment by liuyangming** [comment]
byteTCC为confirm/cancel预先分配一个branchXid只是实现细节。上文说的以事务为单元，是指的全局事务，不同的全局事务在执行confirm/cancel时，即使并发也不会互相影响。

实际上，一个全局事务中的任一个confirm/cancel，在指定的一个时刻，最多只有一个线程在执行：MongoCompensableLock保证当前分支事务只在一个服务实例上操作；TransactionManager/TransactionRecovery保证分支事务只有一个线程在执行。

**Comment by nets7snipper** [comment]
ok 明白了 我自己再去看一下细节 非常感谢
