### ISSUE TITLE
byteTCC 是如何保证 try/confirm/cancle 的调用幂等的?

### ISSUE THREAD

**Issue by daniel-du** [liuyangming/ByteTCC#14]
您好, 请问, byteTCC 是如何保证 try/confirm/cancle 的调用幂等的? 比如, 我在服务A 中调用了 b, c 服务, 然后,  b 出现问题了, 这个时候 c 的cancle 会被调用吗? 这个时候, 如何保证调用幂等的? 谢谢...

**Comment by liuyangming** [comment]
你所举的例子中，c的cancel会不会调用，要取决于：1）c的try操作是否执行；2）c的try操作所参与的事务是否提交。若二者都是，则执行c的cancel逻辑；若任一为否，则不执行c的cancel逻辑。

**ByteTCC只保障confirm/cancel的幂等性**。try阶段service的执行还处于业务系统的控制之中，ByteTCC无法得知一个service被多次调用是由于业务需要还是因重试导致，因此ByteTCC不提供try阶段service的幂等性保障。

ByteTCC通过接管spring的事务管理功能，可以精确的获取到每个事务的commit/rollback情况；通过拦截TCC型service的执行，可以将TCC型service与其参与的事务关联起来，从而获知具体某个TCC型service的执行是否有效（service执行并被提交）；结合ByteTCC的事务日志机制，因此，可以避免一个service（confirm/cancel）被重复执行多次。

**Comment by daniel-du** [comment]
赞, 非常感谢你的回答.
