### ISSUE TITLE
confirm和cancel失败时的重新处理机制问题

### ISSUE THREAD

**Issue by xp331331** [liuyangming/ByteTCC#39]
confirm和cancel失败时，处理机制是每分钟重新请求一次直到成功吗？
有没有对失败处理日志的自动清空机制？

**Comment by liuyangming** [comment]
Confirm/Cancel失败后，目前是固定间隔时间重试一次（可自定义），后续版本将考虑让该间隔时间指数递增。。。
失败的事务，其日志不能删除/清空。

**Comment by xp331331** [comment]
了解，感谢答复。
