### ISSUE TITLE
事务 Context 在分支事务间是如何传递的

### ISSUE THREAD

**Issue by wujun8** [liuyangming/ByteTCC#46]
请教一个问题，从根事务开始，Context 需要传递到分支事务中，这是在哪里做的能否提示一下？
另外，```org.bytesoft.transaction.TransactionContext``` 是全局事务的，```org.bytesoft.compensable.TransactionContext``` 是分支，这样理解没问题吧；
然后看到这里没有可扩展的字段，比如我需要一个字段来传递到所有分支事务，目前好像无法实现

谢谢

**Comment by liuyangming** [comment]
ByteTCC传递事务上下文用的都是org.bytesoft.compensable.TransactionContext。事务上下文信息目前不支持扩展。

**Comment by wujun8** [comment]
那么涉及到 Remote 调用的，Context 是如何传递过去的？
看到有序列化后写到文件，但是不同服务间如何获取这些信息？

**Comment by liuyangming** [comment]
[org.bytesoft.compensable.TransactionContext就是用于远程调用时传播上下文的。在一个节点内部时，直接通过CompensableManager就可以共享事务数据。具体的执行原理可以参考[开发指南](https://github.com/liuyangming/ByteTCC/wiki/Developer-Guide)。

**Comment by wujun8** [comment]
谢谢回复
看到了分别是通过 Dubbo FIlter 和 spring cloud HandlerInterceptor 来做的
