### ISSUE TITLE
dubbo service filter

### ISSUE THREAD

**Issue by wujun8** [liuyangming/ByteTCC#56]
**希望能允许自定义 filter**

ServiceConfigValidator 限制 filter == "compensable", 可以改为像 ReferenceConfigValidator 一样只要包括 "compensable" 就可以吗？

**Comment by liuyangming** [comment]
感谢建议，下个版本中将予以支持！

**Comment by liuyangming** [comment]
已在0.4.14版本中支持，请使用最新版本！有问题欢迎及时反馈！
