### ISSUE TITLE
TransactionArchiveDeserializer 序列化格式

### ISSUE THREAD

**Issue by wujun8** [liuyangming/ByteTCC#57]
对 TransactionArchive 的序列化采用了自定义格式，其中 Variables 使用了 kryo，这里的考虑是什么呢？

如果事物日志只做多个 TransactionArchive 及 其它对象的分隔符字段、数据长度等格式定义，对象序列化统一使用序列化工具来做，与目前实现相比有什么弊端？

**Comment by liuyangming** [comment]
TransactionArchive的各数据类型是固定的，因此可以使用了自定义格式。自定义格式更精简也更有利于解析，不会因为序列化框架更换而受影响。
variables是一个Map，其value可能会有不同的类型，不太适合自定义格式；此外，相对于其他信息而言，variables也并非必需的信息。因此，目前使用文件存储事务日志时，暂定使用hessian/kryo来做序列化。
