### ISSUE TITLE
TransactionContext#coordinator always true

### ISSUE THREAD

**Issue by wujun8** [liuyangming/ByteTCC#60]
请教下，
coordinator 表示当前事务参与者是否协作者？

其值在所有 Context 创建的时候都是赋值 coordinator 为 true 的，值为 false 是为什么场景准备的？

**Comment by liuyangming** [comment]
事务发起方coordinator始终为true；其他接受远程事务传播的参与方coordinator会为false。

**Comment by wujun8** [comment]
THX
是的， 参与方通过 TransactionContext#clone() ，coordinator 取默认值 false
