### ISSUE TITLE
回滚覆盖场景怎么解决

### ISSUE THREAD

**Issue by harden123** [liuyangming/ByteTCC#63]
打个比方，money值在try阶段已经更新到mysql里可见为1，如果别的事务或者手动把值改为2了，这时候cancel回滚是不是值又回滚为1，覆盖了这中间别人提交的值？

**Comment by liuyangming** [comment]
个人觉得，象money这样的值一般为在原值基础上添加/减少一个金额，应该没你说的这个问题。

不过你说的问题，我理解了。如果存在一个未完成的事务数据被新的事务所修改，后续Cancel可能会无法将该数据恢复到Try操作之前。TCC无法从框架层面处理这类问题，如果存在这样的场景，业务系统可以考虑使用乐观加锁的方式解决。

**Comment by liuyangming** [comment]
首先，对于金额这种操作，我觉得通过set value = value + ? 比 set value = ?这种要略好一点，前者cancel时直接扣减一定金额即可，应该不存在你说的这个问题；
其次，即使你使用set value = ?这种操作方式，也可以考虑使用乐观加锁的方式予以解决。比如：设置一个锁字段比如version，为空时可以修改，非空时表示被其他事务锁定。Try中设置version的值，Confirm/Cancel将其置空。TCC只是提供一种机制，具体得看你业务系统如何规划设计，TCC框架无法对数据加锁，但不表示你业务系统不能对数据加锁。

**Comment by harden123** [comment]
业务系统对数据加分布式锁或者数据库乐观锁，直到Confirm/Cancel才释放的做法，增加了复杂度和代码入侵。我感觉还不如直接用xa风格的2pc，看了另外一个开源分布式事务框架的做法，是代理了连接池，让事务管理器控制mysql的资源管理器，统一最后Confirm的时候再一起commit。

**Comment by harden123** [comment]
业务系统对数据加分布式锁或者数据库乐观锁，直到Confirm/Cancel才释放的做法，增加了复杂度和代码入侵。我感觉还不如直接用xa风格的2pc，看了另外一个开源分布式事务框架的做法，是代理了连接池，让事务管理器控制mysql的资源管理器，统一最后Confirm的时候再一起commit。

**Comment by harden123** [comment]
是否考虑实现对支持XA/2PC的RM进行调度完成提交，补偿则由RM自己回滚控制。
对不支持的RM手动进行提交，手动补偿。

**Comment by liuyangming** [comment]
XA/2PC提供的是强一致性事务保障，如果你能接受XA/2PC的一系列缺点（比如性能不足、事务阻塞等），那么它就已经能完全能满足你的事务性需求了，没任何必要再使用补偿/TCC机制。

如果按你所说的，要在使用XA /2PC基础上再加上补偿机制，那实际上是既承受了XA/2PC的劣势，又没有得到XA/2PC所带来的便利，还需要手写补偿逻辑。纯粹是为了使用而使用，不明白你选择XA/2PC的用意是什么。

**Comment by harden123** [comment]
XA/2PC目的是为了弥补不支持XA协议的数据源或者中间件，可以进行2pc补偿逻辑，同时让支持XA协议的数据库控制默认事务行为。应该来说是XA的变体，集合了XA和2PC的优点吧。我是觉得，tcc模式没有隔离性的保证，在cofirm阶段就提交了本地事务会有脏数据的风险。

**Comment by liuyangming** [comment]
> XA/2PC目的是为了弥补不支持XA协议的数据源或者中间件，可以进行2pc补偿逻辑，同时让支持XA协议的数据库控制默认事务行为。应该来说是XA的变体，集合了XA和2PC的优点吧。    

XA/2PC本身就必须依赖RM对XA的支持，如何做到弥补不支持XA协议的数据源/中间件？要用XA/2PC就要求全部的RM都支持XA，否则根本无法协调全局事务进行两阶段提交。
你可能不太了解XA/2PC。2PC是一种事务机制，XA是2PC的业界规范，不存在集合XA和2PC优点的说法。

另外，不明白你所说的2PC补偿逻辑是什么意思？如前面回复中所说的，既然用了2PC就没什么必要再用补偿机制了。

**Comment by harden123** [comment]
是我混淆了xa和2pc的概念。我真正想表达的意思是tcc和xa能否结合，保证支持xa规范的数据源达到强一致性，其他不支持xa的数据源达到最终一致性。

**Comment by liuyangming** [comment]
既然全局事务中存在不支持XA的资源，你自己也说只能达到最终一致性，那么全局事务就更不可能是强一致性而也只能是达到最终一致的了。
问题在于，全局事务最终一致性，只用TCC也能做到，为什么要引入XA/2PC呢？毕竟，引入XA/2PC会带来它那些为人诟病的弊端（性能不足、事务阻塞等），而你说的这种方案却又完全没有用到XA/2PC的优势。

**Comment by harden123** [comment]
全局事务中存在不支持XA的资源比如缓存中间件，消息中间件，但是那部分资源允许最终一致性可能不会影响业务的精确性，但业务准确性我觉得还是要靠mysql和oracle等支持xa的数据源。所以我是想能不能有个折中的方案。

**Comment by liuyangming** [comment]
一般来说，很少有缓存需要参与事务的。一些传统的消息中间件，比如ActiveMQ，也是支持XA/2PC的。而kafka/rocketmq这些MQ，我相信可能也是出于性能考虑才不支持XA/2PC。既然你已经要用XA了，为何不选择支持XA的MQ，而选择不支持的呢？

一个全局事务，要么是强一致性，要么就是最终一致性，是没有什么折中的方案的。选择XA/2PC必定是看中了其对事务的强一致性保障，如果再加上一些不支持XA的资源，使得事务保障性降为最终一致性，那何必还坚持用XA呢？都用TCC不可以么？毕竟，XA一些为人诟病的弊端就摆在那里。

你说的方案并非一定不可行，只是不可取。相当于放弃了XA/2PC和TCC的各自优点，而将XA/2PC和TCC的各自弊端都整合到了一起。

**Comment by harden123** [comment]
我理解你的说法了，那请教下，如果想要实现xa的强一致性又不想调高数据库序列化隔离级别，能不能在tcc下对正在操作的资源读写都加锁，这样做是不是既保证了强一致性，可取吗？

**Comment by liuyangming** [comment]
这不是可取不可取的问题，单个RM在自己的本地事务中对某些数据加锁，理论上对全局事务的一致性没有任何影响。

**Comment by harden123** [comment]
如果不对资源加锁，即使做到了全局事务的一致性，但是很难避免其他脏读和覆盖更新的产生吧?XA分布式事务下，mysql官方都建议将隔离级别最好调至Serializable，避免脏读对业务产生影响。

**Comment by liuyangming** [comment]
要避免脏读，设置成读取已提交即可，何须Serializeable？恐怕也没人觉得TCC能取代XA吧，不同的方案而已，选择适合自己需求的就好。

这个issue已经偏离原来的主题了，如果有事务相关的疑问，另开issue或者加qq群里讨论吧。
