### ISSUE TITLE
0.4.14版本找不到org.bytesoft.bytejta.supports.jdbc.LocalXADataSource

### ISSUE THREAD

**Issue by dawe001** [liuyangming/ByteTCC#69]
版本<dependency>
            <groupId>org.bytesoft</groupId>
            <artifactId>bytetcc-supports-springcloud</artifactId>
            <version>0.4.14</version>
        </dependency>

**Comment by dawe001** [comment]
org.bytesoft.bytejta.supports.jdbc这个包里并没有LocalXADataSource

**Comment by liuyangming** [comment]
ByteTCC依赖ByteJTA来处理本地事务，LocalXAResource这个类定义在ByteJTA工程中。

**Comment by dawe001** [comment]
[](url)
![image](https://user-images.githubusercontent.com/22997712/42503750-1712d030-846c-11e8-943e-e48498671049.png)
依赖这样的
