### ISSUE TITLE
跨系统事务中有 nosql 数据库，ByteTCC ok 吗？

### ISSUE THREAD

**Issue by zengbotang** [liuyangming/ByteTCC#7]

**Comment by liuyangming** [comment]
ByteTCC依赖RM对本地事务的支持来控制TCC全局事务，因此：如果NoSQL数据库不支持事务，ByteTCC就支持不了；若NoSQL支持事务，ByteTCC就可以支持（视情况可能还需要一点集成工作要做）。

**Comment by hanbin** [comment]
@liuyangming TCC不是在业务层进行操作的么？为什么ByteTCC不能支持不支持事务的NoSQL？

**Comment by liuyangming** [comment]
TCC虽然是基于业务层的Try-Confirm-Cancel来控制事务的，但不要忘了，它毕竟是事务管理机制，TCC对事务的控制也依赖Try-Confirm-Cancel等业务操作的原子性、一致性保证。

举个例子，假设你Try操作执行了10个NoSQL的写库操作，中途出错中断，然而可能有n个（因为故障原因具体数目无从得知，但0<n<10）已经写入NoSQL，10-n个尚未执行。这中情况下，因为NoSQL不支持事务，就会导致cancel逻辑的编写将会及其复杂，甚至不可能实现。

相反，对于支持事务的RDBS，则处理就会不一样。一旦Try操作中断，只需要通过rollback其DB事务，就可以将前n个已执行的操作回撤掉，不必依赖cancel。而相应的cancel逻辑也只需要考虑回撤全部的Try操作，不必考虑Try只执行了一部分的情况。
