### ISSUE TITLE
非spring容器框架是否支持

### ISSUE THREAD

**Issue by liangchengzhi** [liuyangming/ByteTCC#74]
请问是否支持非spring容器的框架(nutz)，其管理bean和事务都是nutz自带的？

**Comment by liuyangming** [comment]
ByteTCC并非仅为spring容器而设计，其他容器也可以支持，但有所约束：需要支持JTA、CDI等规范。

ByteTCC目前分5个子工程：
1. bytetcc-common
1. bytetcc-core
1. bytetcc-supports
1. bytetcc-supports-springcloud
1. bytetcc-supports-dubbo    

其中，bytetcc-common为公共部分，bytetcc-core为事务处理的核心模块，这两个模块都不依赖特定的容器；另外的bytetcc-supports、bytetcc-supports-springcloud、bytetcc-supports-dubbo这三个工程则是基于spring容器。若要使用其他容器，就需要相应地自己做一些集成类的定制工作。

**Comment by liuyangming** [comment]
你可能看的不太仔细，org.bytesoft.bytetcc.work包下至少就有两个定时任务：CompensableWork、CleanupWork。

ByteTCC可以最大程度的保障事务一致性，不论是网络故障，还是是jvm宕机，又或者是db宕机等故障，ByteTCC都能处理，如果你不太放心不妨自己动手模拟一下这些故障测试一下ByteTCC的可靠性。

**Comment by liangchengzhi** [comment]
好的，我继续学习
