### ISSUE TITLE
对 bytetcc-supports-dubbo 的负载均衡扩展的一点疑问

### ISSUE THREAD

**Issue by assault65535** [liuyangming/ByteTCC#76]
我注意到该模块的 `spi.CompensableLoadBalancer` 类实现的是 bytejta 里面的 `ILoadBalancer` 接口，而 bytetcc 里面的 `ILoadBalancer` 接口却没有子类。

实际上，在调试 A 服务调用具有 2 个实例的 B 服务的场景的时候也发现 A 服务在加载 Dubbo 扩展点的时候报了
`IllegalStateException Input type org.bytesoft.bytetcc.supports.dubbo.spi.CompensableLoadBalancer not implement Extension org.bytesoft.bytetcc.supports.dubbo.ext.ILoadBalancer` 
这样的异常，将这个类的实现接口改成 bytetcc 里面的 `ILoadBalancer` 则可正常加载并执行事务。
请问这样的修改是否是对的？

**Comment by liuyangming** [comment]
已在0.4.17版本中修复，请使用最新版本！
