### ISSUE TITLE
代码有点牛头不对马嘴哎

### ISSUE THREAD

**Issue by wyy0506** [liuyangming/ByteTCC#77]
代码有点牛头不对马嘴哎

import org.bytesoft.transaction.remote.RemoteCoordinator;
import org.bytesoft.transaction.supports.resource.XAResourceDescriptor;
import org.bytesoft.transaction.supports.serialize.XAResourceDeserializer;

这些类以及其他有些根本看不到，本来还想研究一下，只能换一个项目了

**Comment by liuyangming** [comment]
ByteTCC依赖ByteJTA管理本地事务，ByteTCC & ByteJTA的代码都放在github上，已发布的版本源码也上传到了mvn中心仓库。哪怕你懒得从github上下载，也可以直接用mvn dependency:sources命令下载到。
就这样都找不到，不知道你是怎么好意思在issue里发专帖抱怨的。。。issue区是用来讨论问题的，即使你不想多费心思，也请不要影响其他人。

**Comment by wyy0506** [comment]
大家好，我可能没看见，我眼神不好，研究研究，能有中国人具有贡献精神挺好
