### ISSUE TITLE
关于跨进程事务传播

### ISSUE THREAD

**Issue by gumandy** [liuyangming/ByteTCC#80]
事务传播支持跨进程的传播吗？
父进程开启事务传播到多个子进程事务，任何子进程的事务try失败通知父进程回滚，这里的父进程回滚的意思是**自己回滚以及通知所有子进程事务回滚**
也就是无论父子进程哪个事务失败都通知属于同一根事务的其他参与事务回滚

**Comment by liuyangming** [comment]
支持。跨进程、跨服务器只是一个最基本的场景。具体说明请参考开发指南中的执行原理介绍：
https://github.com/liuyangming/ByteTCC/wiki/Developer-Guide
