### ISSUE TITLE
bytetcc与bytejta配置文件有冲突

### ISSUE THREAD

**Issue by zrweng** [liuyangming/ByteTCC#85]
bytetcc依赖bytejta ，其中bytejta-supports-task.xml 与 bytetcc-supports-task.xml配置冲突：

No qualifying bean of type [javax.resource.spi.work.WorkManager] is defined: expected single matching bean but found 2: transactionWorkManager,compensableWorkManager

去掉哪一个？

**Comment by liuyangming** [comment]
使用ByteTCC时，不需要ByteJTA的配置文件，不要显式的引入ByteJTA的配置文件。参考ByteTCC-sample样例中的配置即可。

**Comment by zrweng** [comment]
那只能指定加载配置文件，当前出错原因是默认加载类路径下所有xml文件
