### ISSUE TITLE
MongoCompensableLogger endpoint属性应该怎么设置？

### ISSUE THREAD

**Issue by zrweng** [liuyangming/ByteTCC#86]
默认未设置有异常：

````java

public void updateTransaction(TransactionArchive archive) {
		try {
			String application = CommonUtils.getApplication(this.endpoint);
			String databaseName = application.replaceAll("\\W", "_");
             .....
````

**Comment by liuyangming** [comment]
endpoint是ByteTCC自行设置的，但需要dubbo/SpringCloud按各自支持的格式指定应用名称和端口号，以便ByteTCC可以找到。比如，SpringCloud需要指定spring.application.name和server.port这两个配置。

**Comment by zrweng** [comment]
好几个Bean都需要endpoint属性设置，最好改为Endpoint对象，这样Bean可以统一定义，如:
@Resource
Endpoint endpoint;

**Comment by zrweng** [comment]
> endpoint是ByteTCC自行设置的，但需要dubbo/SpringCloud按各自支持的格式指定应用名称和端口号，以便ByteTCC可以找到。比如，SpringCloud需要指定spring.application.name和server.port这两个配置。

我的理解是，endpoint不需要依赖dubbo或server配置吧。如果一个应用是基于Spring Cloud开发，但又使用了Dubbo 可怎么办？

**Comment by liuyangming** [comment]
ByteTCC要求获取应用名称和端口这两个配置，既然dubbo/SpringCloud已有相应配置，再另行创建两个配置项并无必要。即使真的有应用既使用SpringCloud又使用dubbo，那么在集成ByteTCC时也是要显式的引入DubboSupportConfiguration/SpringCloudConfiguration配置类的，引入哪一个配置类，ByteTCC就用相应那一个相应的应用名称、端口配置信息。
